# Volt Analytics

## Import Dependencies

In [1]:
import os
import datetime as dt
import numpy as np
import pandas as pd
import openpyxl as Workbook

pd.set_option('display.max_rows', 500)

In [2]:
currentDate =  dt.datetime.today().date()
currentDate

datetime.date(2017, 9, 19)

## Read in CSV files

In [3]:
#Volt Daily Data
voltDailyData = pd.read_csv('data/voltdailydata_' + currentDate.strftime('%Y%m%d') + '.csv')
voltDailyData['Date'] = pd.to_datetime(voltDailyData['Date'])
voltDailyData['Date'] = voltDailyData['Date'].dt.date

In [4]:
voltDailyData.head()

         Date  MilesDriven  EvMilesDriven  GallonsBurned
0  2017-06-25        163.7           52.6        3.03005
1  2017-06-26        202.4           42.5        4.15543
2  2017-06-27        202.3           53.8        3.97314
3  2017-06-28        197.7           52.4        3.93617
4  2017-06-29        192.6           45.2        3.83577

In [5]:
# Calculate total ICE (Internal Combustion Engine) miles driven
voltDailyData = voltDailyData.rename(columns = {'MilesDriven':'TotalMilesDriven'})
voltDailyData['TotalICEMiles'] = voltDailyData['TotalMilesDriven'] - voltDailyData['EvMilesDriven']
voltDailyData.head()

         Date  TotalMilesDriven  EvMilesDriven  GallonsBurned  TotalICEMiles
0  2017-06-25             163.7           52.6        3.03005          111.1
1  2017-06-26             202.4           42.5        4.15543          159.9
2  2017-06-27             202.3           53.8        3.97314          148.5
3  2017-06-28             197.7           52.4        3.93617          145.3
4  2017-06-29             192.6           45.2        3.83577          147.4

In [6]:
# Create new DailyMPG Column, round values after adding new column
voltDailyData['DailyMPG'] = voltDailyData['TotalMilesDriven'] / voltDailyData['GallonsBurned']
voltDailyData['DailyMPG'] = pd.to_numeric(voltDailyData['DailyMPG'], errors='coerse')
voltDailyData = voltDailyData.replace(np.nan, 0)
voltDailyData = voltDailyData.round(2)
voltDailyData.head()

,Date,TotalMilesDriven,EvMilesDriven,GallonsBurned,TotalICEMiles,DailyMPG
0,2017-06-25,163.7,52.6,3.03,111.1,54.03
1,2017-06-26,202.4,42.5,4.16,159.9,48.71
2,2017-06-27,202.3,53.8,3.97,148.5,50.92
3,2017-06-28,197.7,52.4,3.94,145.3,50.23
4,2017-06-29,192.6,45.2,3.84,147.4,50.21

In [7]:
# Add '250+' miles to any DailyMPG value that has a value of infinity
# Why 250+? That's the "infinity mileage" that the volt displays in car

voltDailyData = voltDailyData.replace(np.inf, '250+')
voltDailyData.tail()

,Date,TotalMilesDriven,EvMilesDriven,GallonsBurned,TotalICEMiles,DailyMPG
62,2017-09-11,0.0,0.0,0.00,0.0,0
63,2017-09-12,196.6,0.0,4.93,196.6,39.86
64,2017-09-13,122.0,0.0,3.30,122.0,36.95
65,2017-09-18,36.2,36.2,0.00,0.0,250+
66,2017-09-19,31.8,31.8,0.00,0.0,250+

In [8]:
voltDailyData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 6 columns):
Date                67 non-null object
TotalMilesDriven    67 non-null float64
EvMilesDriven       67 non-null float64
GallonsBurned       67 non-null float64
TotalICEMiles       67 non-null float64
DailyMPG            67 non-null object
dtypes: float64(4), object(2)
memory usage: 3.2+ KB

## Volt Readings

In [9]:
#Volt Readings throughout the day (usually two), convert Timestamp to datetime object
voltReadings = pd.read_csv('data/voltdata_' + currentDate.strftime('%Y%m%d') + '.csv')
voltReadings.rename(columns = {'LocalTimestamp':'Date', 'GallonsBurned': 'LifeTimeGalBurned'}, inplace=True)
voltReadings['Date'] = pd.to_datetime(voltReadings['Date'])

voltReadings.head()

,BatteryLevel,ChargeState,OilLife,TirePressure_LF,TirePressure_LR,TirePressure_RF,TirePressure_RR,Date,LifeTimeGalBurned,LifetimeFuelEcon,LifetimeEvMiles,LifetimeMiles,LastTripFuelEcon,LastTripEvMiles,LastTripMiles,GallonsOfGas
0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2017-09-19 18:26:49,760.2289,64.89379,20635.22148,49334.13224,0.0,0.0,0.0,3.17535
1,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2017-09-18 19:30:13,760.2289,64.85196,20603.41349,49302.33046,0.0,0.0,0.0,3.17535
2,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2017-09-18 06:39:52,760.2289,64.80439,20567.26211,49266.17287,0.0,0.0,0.0,3.17535
3,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2017-09-17 18:44:08,760.2289,64.80438,20567.26211,49266.16044,0.0,0.0,0.0,3.21233
4,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2017-09-17 06:02:14,760.2289,64.80438,20567.26211,49266.16044,0.0,0.0,0.0,3.21233

In [10]:
# Select only columns desired
voltReadings = voltReadings[['Date', 'LifeTimeGalBurned', 'LifetimeFuelEcon', 'LifetimeEvMiles','LifetimeMiles']]

In [11]:
#Calculate LifetimeICEMiles
voltReadings['LifetimeICEMiles'] = voltReadings['LifetimeMiles'] - voltReadings['LifetimeEvMiles']

In [12]:
# Sort based on timestamp, reorder columns, round values
voltReadings.sort_values(by='Date', inplace=True)
voltReadings = voltReadings[['Date', 'LifeTimeGalBurned','LifetimeFuelEcon','LifetimeEvMiles','LifetimeICEMiles','LifetimeMiles']]
voltReadings = voltReadings.round(2)
voltReadings

,Date,LifeTimeGalBurned,LifetimeFuelEcon,LifetimeEvMiles,LifetimeMiles,LifetimeICEMiles
167,2017-06-24 17:31:19,593.83,68.35,17941.91,40585.45,22643.54
166,2017-06-25 05:35:50,593.83,68.35,17941.91,40585.45,22643.54
165,2017-06-25 17:51:57,596.65,68.27,17988.50,40734.80,22746.30
164,2017-06-26 05:52:46,596.86,68.27,17994.46,40749.16,22754.70
163,2017-06-26 19:15:25,601.02,68.14,18036.93,40951.55,22914.62
162,2017-06-27 06:58:20,601.50,68.13,18049.11,40980.32,22931.22
161,2017-06-27 17:43:14,604.19,68.05,18084.05,41116.79,23032.74
160,2017-06-28 05:34:27,604.99,68.02,18090.77,41153.86,23063.09
159,2017-06-28 17:35:10,608.17,67.93,18130.94,41311.50,23180.56
158,2017-06-29 05:36:46,608.92,67.91,18143.16,41351.56,23208.41
157,2017-06-29 18:01:14,612.76,67.80,18188.35,41544.16,23355.81
156,2017-06-30 07:19:03,613.11,67.78,18188.35,41556.39,23368.04
155,2017-06-30 18:42:53,613.11,67.78,18188.35,41556.39,23368.04
154,2017-07-01 07:23:44,613.11,67.78,18189.29,41557.34,23368.04
153,2017-07-01 18:57:13,615.91,67.67,18221.60,41675.86,23454.26
152,2017-07-02 06:56:42,617.78,67.61,18244.15,41770.73,23526.58
151,2017-07-02 18:54:31,617.78,67.62,18247.15,41773.73,23526.58
150,2017-07-03 06:39:16,617.78,67.62,18250.34,41776.92,23526.58
149,2017-07-03 18:54:10,618.53,67.59,18256.11,41809.13,23553.02
148,2017-07-04 06:51:32,618.53,67.59,18256.11,41809.13,23553.02
147,2017-07-04 18:48:03,618.53,67.61,18266.88,41819.89,23553.01
146,2017-07-05 07:13:52,619.45,67.61,18295.09,41879.55,23584.47
145,2017-07-05 18:44:09,622.36,67.51,18324.70,42016.87,23692.16
144,2017-07-06 06:56:17,622.36,67.51,18324.70,42016.87,23692.16
143,2017-07-06 18:07:56,622.36,67.53,18337.03,42029.20,23692.17
142,2017-07-07 07:06:20,622.36,67.53,18337.03,42029.20,23692.17
141,2017-07-07 17:58:03,622.36,67.53,18337.03,42029.20,23692.17
140,2017-07-08 05:59:27,622.36,67.54,18343.48,42035.64,23692.16
139,2017-07-08 17:38:35,622.36,67.54,18343.48,42035.64,23692.16
138,2017-07-09 05:40:50,622.36,67.55,18346.48,42038.64,23692.16
137,2017-07-09 18:01:33,622.36,67.55,18347.35,42039.51,23692.16
136,2017-07-10 06:35:08,622.36,67.56,18352.68,42044.84,23692.16
135,2017-07-10 18:26:26,625.97,67.47,18412.71,42236.87,23824.16
134,2017-07-11 08:40:59,628.24,67.41,18451.72,42350.27,23898.55
133,2017-07-11 19:08:24,630.19,67.36,18475.92,42449.27,23973.35
132,2017-07-12 06:42:13,630.78,67.35,18485.76,42483.13,23997.37
131,2017-07-12 18:57:59,634.12,67.26,18541.47,42652.91,24111.43
130,2017-07-13 09:36:20,636.07,67.23,18582.36,42762.86,24180.50
129,2017-07-13 18:35:11,636.73,67.21,18596.33,42792.96,24196.63
128,2017-07-14 07:20:48,638.46,67.17,18623.96,42886.19,24262.23
127,2017-07-14 17:43:59,638.46,67.17,18623.96,42886.24,24262.28
126,2017-07-15 06:43:17,638.46,67.17,18623.96,42886.24,24262.28
125,2017-07-15 17:53:16,638.46,67.19,18633.94,42896.22,24262.28
124,2017-07-16 06:34:51,638.46,67.20,18640.95,42903.23,24262.28
123,2017-07-16 18:58:22,638.46,67.22,18655.98,42918.26,24262.28
122,2017-07-17 18:55:15,642.49,67.12,18701.91,43122.02,24420.11
121,2017-07-18 07:16:37,643.54,67.11,18726.81,43185.48,24458.67
120,2017-07-18 17:54:19,646.24,67.04,18761.50,43321.81,24560.31
119,2017-07-19 05:37:32,646.35,67.03,18763.83,43326.36,24562.54
118,2017-07-19 17:33:15,649.30,66.97,18818.13,43484.45,24666.32
117,2017-07-20 04:29:06,650.15,66.94,18826.17,43523.99,24697.83
116,2017-07-20 18:57:23,653.72,66.88,18892.47,43721.80,24829.33
115,2017-07-21 07:36:48,654.18,66.86,18892.47,43741.22,24848.75
114,2017-07-21 18:52:33,654.18,66.87,18897.56,43746.31,24848.75
113,2017-07-22 07:36:00,654.18,66.88,18901.09,43749.84,24848.75
112,2017-07-22 19:05:18,654.18,66.88,18901.11,43749.86,24848.75
111,2017-07-23 07:48:34,654.18,66.88,18901.11,43749.86,24848.75
110,2017-07-23 19:52:07,654.18,66.88,18904.65,43753.40,24848.75
109,2017-07-24 06:55:03,655.04,66.86,18914.73,43795.83,24881.11
108,2017-07-24 19:12:59,657.97,66.80,18963.99,43951.39,24987.40
107,2017-07-25 07:06:59,658.76,66.78,18973.93,43990.43,25016.50
106,2017-07-25 18:29:46,661.58,66.73,19035.68,44149.40,25113.73
105,2017-07-26 09:13:20,663.46,66.70,19071.75,44249.82,25178.08
104,2017-07-26 20:14:24,664.03,66.70,19097.76,44289.44,25191.68
103,2017-07-27 07:40:49,664.03,66.70,19097.76,44289.46,25191.70
102,2017-07-27 19:00:03,664.27,66.74,19136.08,44336.02,25199.94
101,2017-07-28 05:40:50,664.27,66.74,19136.08,44336.02,25199.94
100,2017-07-28 18:08:07,665.92,66.74,19174.97,44442.85,25267.88
99,2017-07-29 05:58:35,666.23,66.73,19174.97,44457.97,25282.99
98,2017-07-29 17:51:07,666.23,66.77,19199.56,44482.55,25282.99
97,2017-07-30 06:17:41,666.23,66.79,19213.90,44496.89,25282.99
96,2017-07-30 17:35:54,672.11,66.52,19218.66,44711.13,25492.47
95,2017-07-31 07:17:53,676.01,66.38,19230.80,44876.93,25646.13
94,2017-07-31 20:24:09,679.27,66.32,19276.66,45047.62,25770.95
93,2017-08-01 07:34:23,680.43,66.31,19304.53,45117.61,25813.08
92,2017-08-01 19:17:57,683.10,66.24,19331.17,45246.00,25914.83
91,2017-08-02 07:33:42,683.90,66.23,19345.96,45292.20,25946.24
90,2017-08-02 17:27:31,685.75,66.20,19385.66,45399.19,26013.52
89,2017-08-03 05:26:52,686.80,66.17,19385.66,45444.26,26058.59
88,2017-08-03 17:26:57,690.42,66.09,19443.03,45629.18,26186.15
87,2017-08-04 05:27:19,691.02,66.06,19443.03,45651.69,26208.65
86,2017-08-04 18:20:52,692.97,66.03,19475.07,45757.91,26282.85
85,2017-08-05 07:49:19,694.69,65.97,19475.48,45825.32,26349.84
84,2017-08-05 19:04:45,694.82,65.97,19483.66,45836.78,26353.12
83,2017-08-06 07:01:29,694.82,65.99,19498.32,45851.43,26353.12
82,2017-08-06 18:51:47,695.06,66.03,19535.82,45893.89,26358.06
81,2017-08-07 05:25:36,696.17,66.00,19544.06,45949.18,26405.12
80,2017-08-07 17:53:59,696.17,66.00,19544.06,45949.21,26405.16
79,2017-08-08 05:22:17,696.17,66.00,19544.06,45949.21,26405.16
78,2017-08-08 18:18:47,700.02,65.92,19608.40,46147.01,26538.61
77,2017-08-09 07:41:27,702.04,65.87,19639.29,46245.08,26605.79
76,2017-08-09 17:39:41,703.95,65.83,19667.06,46343.07,26676.01
75,2017-08-10 05:25:34,703.95,65.83,19667.06,46343.07,26676.01
74,2017-08-10 19:07:07,707.54,65.78,19739.07,46541.22,26802.15
73,2017-08-11 07:31:10,707.54,65.78,19739.07,46541.22,26802.15
72,2017-08-11 18:23:15,707.54,65.78,19739.07,46541.22,26802.15
71,2017-08-12 07:30:18,707.54,65.78,19739.07,46541.22,26802.15
70,2017-08-12 19:03:28,707.54,65.78,19739.07,46541.22,26802.15
69,2017-08-13 07:41:44,707.54,65.78,19739.07,46541.22,26802.15
68,2017-08-13 18:58:21,707.54,65.79,19745.32,46547.47,26802.14
67,2017-08-14 06:50:34,708.86,65.74,19748.54,46599.56,26851.03
66,2017-08-14 19:43:19,711.26,65.72,19813.34,46744.06,26930.72
65,2017-08-15 18:35:30,715.05,65.65,19874.27,46942.02,27067.76
64,2017-08-16 06:18:35,715.91,65.62,19876.82,46977.41,27100.59
63,2017-08-16 17:11:27,717.16,65.62,19926.26,47063.26,27137.00
62,2017-08-17 05:27:06,717.16,65.62,19926.26,47063.26,27137.00
61,2017-08-17 17:22:42,718.16,65.64,19975.12,47141.43,27166.30
60,2017-08-18 05:44:44,718.97,65.63,19985.50,47184.80,27199.30
59,2017-08-18 18:33:07,718.97,65.63,19985.50,47184.80,27199.30
58,2017-08-19 06:55:47,718.97,65.63,19985.50,47184.80,27199.30
57,2017-08-19 18:18:43,718.97,65.63,19985.50,47184.82,27199.32
56,2017-08-20 06:24:03,718.97,65.63,19985.50,47184.82,27199.32
55,2017-08-20 17:18:56,718.97,65.63,19985.50,47184.84,27199.34
54,2017-08-21 05:59:27,719.11,65.63,19988.04,47192.19,27204.15
53,2017-08-21 19:04:35,722.87,65.55,20041.05,47381.82,27340.77
52,2017-08-22 08:51:41,724.76,65.51,20076.50,47480.67,27404.17
51,2017-08-22 18:39:50,726.87,65.46,20097.95,47580.50,27482.55
50,2017-08-23 07:23:00,726.87,65.46,20097.95,47580.50,27482.55
49,2017-08-23 18:45:23,726.87,65.50,20129.18,47611.72,27482.55
48,2017-08-24 09:33:49,728.75,65.47,20163.07,47710.86,27547.80
47,2017-08-24 18:55:36,729.97,65.45,20191.18,47777.09,27585.91
46,2017-08-25 05:26:49,731.24,65.41,20191.18,47828.17,27636.99
45,2017-08-25 17:21:51,731.24,65.45,20222.39,47859.39,27637.00
44,2017-08-26 07:39:20,731.24,65.45,20222.39,47859.39,27637.00
43,2017-08-26 19:10:59,731.24,65.45,20222.42,47859.42,27637.00
42,2017-08-27 07:35:49,731.24,65.45,20222.42,47859.42,27637.00
41,2017-08-27 19:30:53,731.24,65.45,20222.44,47859.44,27637.00
40,2017-08-28 08:11:23,731.24,65.45,20222.44,47859.44,27637.00
39,2017-08-29 08:34:31,733.14,65.41,20256.11,47958.07,27701.96
38,2017-08-29 18:13:26,734.92,65.39,20282.34,48056.66,27774.31
37,2017-08-30 07:13:34,736.22,65.35,20286.79,48109.51,27822.72
36,2017-08-30 17:58:02,738.49,65.32,20343.39,48239.49,27896.10
35,2017-08-31 07:36:37,738.88,65.31,20343.39,48254.63,27911.24
34,2017-08-31 18:41:31,738.88,65.31,20343.39,48254.63,27911.24
33,2017-09-01 05:39:26,738.88,65.31,20343.39,48254.63,27911.24
32,2017-09-01 17:52:13,738.88,65.32,20354.49,48265.73,27911.24
31,2017-09-02 07:40:50,738.88,65.32,20354.49,48265.73,27911.24
30,2017-09-02 18:03:02,738.88,65.32,20354.49,48265.73,27911.24
29,2017-09-03 06:45:56,738.88,65.32,20354.49,48265.73,27911.24
28,2017-09-03 18:51:53,738.88,65.32,20354.49,48265.73,27911.24
27,2017-09-04 07:15:21,738.88,65.32,20354.49,48265.73,27911.24
26,2017-09-04 18:52:20,738.88,65.32,20354.49,48265.73,27911.24
25,2017-09-05 08:02:40,741.06,65.26,20380.96,48364.05,27983.09
24,2017-09-05 18:12:25,743.08,65.21,20398.06,48456.59,28058.53
23,2017-09-06 06:36:57,743.88,65.18,20398.06,48484.31,28086.25
22,2017-09-06 18:26:01,746.62,65.08,20398.06,48589.08,28191.02
21,2017-09-07 06:42:58,746.69,65.10,20416.96,48610.39,28193.43
20,2017-09-07 18:16:41,747.46,65.09,20441.99,48655.94,28213.95
19,2017-09-08 05:38:10,747.53,65.09,20441.99,48659.86,28217.87
18,2017-09-08 18:14:14,749.27,65.09,20492.18,48770.47,28278.29
17,2017-09-09 07:58:32,749.56,65.08,20492.18,48780.63,28288.45
16,2017-09-09 17:34:06,749.56,65.08,20492.18,48780.64,28288.46
15,2017-09-10 06:18:17,749.56,65.08,20492.18,48780.64,28288.46
14,2017-09-10 17:38:13,749.56,65.08,20492.18,48780.64,28288.46
13,2017-09-11 05:47:33,749.56,65.08,20492.18,48780.64,28288.46
12,2017-09-11 18:26:06,749.56,65.08,20492.18,48780.64,28288.46
11,2017-09-12 05:38:50,749.56,65.08,20492.18,48780.64,28288.46
10,2017-09-12 17:37:09,752.57,64.97,20492.18,48895.32,28403.14
9,2017-09-13 05:39:47,754.49,64.91,20492.18,48977.28,28485.10
8,2017-09-13 18:12:52,757.79,64.79,20492.18,49099.25,28607.07
7,2017-09-14 05:38:26,757.79,64.79,20492.18,49099.25,28607.07
6,2017-09-14 17:53:25,757.92,64.81,20510.61,49122.58,28611.97
5,2017-09-15 06:53:09,758.28,64.84,20547.33,49168.33,28620.99
4,2017-09-17 06:02:14,760.23,64.80,20567.26,49266.16,28698.90
3,2017-09-17 18:44:08,760.23,64.80,20567.26,49266.16,28698.90
2,2017-09-18 06:39:52,760.23,64.80,20567.26,49266.17,28698.91
1,2017-09-18 19:30:13,760.23,64.85,20603.41,49302.33,28698.92
0,2017-09-19 18:26:49,760.23,64.89,20635.22,49334.13,28698.91

In [13]:
voltReadings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 168 entries, 167 to 0
Data columns (total 6 columns):
Date                 168 non-null datetime64[ns]
LifeTimeGalBurned    168 non-null float64
LifetimeFuelEcon     168 non-null float64
LifetimeEvMiles      168 non-null float64
LifetimeMiles        168 non-null float64
LifetimeICEMiles     168 non-null float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 9.2 KB